### ISSUE TITLE
Problem with the tests

### ISSUE THREAD

**Issue by JaimePSantos** [den01-python-programming-exercises/exercise-3-21-av-club-JaimePSantos#1]
Hello,
Im not sure what is wrong with my solution, i followed the readme guidelines and built a list with input strings. Then i split each string in the input list string by empty spaces and foreach piece of that string i compared it to "av" and printed it if it matched. The error is this:
`E       AssertionError: assert ['', '', '', 'java', 'navy', '', '', '', '', 'have', 'favourite', 'flavour'] == ['', 'java', '', 'navy', '', '', 'have', 'favourite', 'flavour', '', '', '']
E         At index 1 diff: '' != 'java'
E         Full diff:
E         - ['', 'java', '', 'navy', '', '', 'have', 'favourite', 'flavour', '', '', '']
E         ?              ----                                              ------------
E         + ['', '', '', 'java', 'navy', '', '', '', '', 'have', 'favourite', 'flavour']
E         ?     ++++++++                        ++++++++`

Thank you!

**Comment by Scott3142** [comment]
Your code does work, but only prints the user-inputted strings that include `av` once the program has finished.

The intended functionality is:

- User inputs string.
- If string contains `av`, string is immediately outputted to the screen.
- If empty string, end program.

So, basically, you need to check your loops and move the `print` statement to a different place.

**Comment by JaimePSantos** [comment]
That fixed it, thank you very much!
